// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR9pf6SWNsO7Qpav1S7yKZQ2muu5tOF0A',
    appId: '1:588349736392:web:03d173a2014702f5f6ecfd',
    messagingSenderId: '588349736392',
    projectId: 'chatapp-29c9b',
    authDomain: 'chatapp-29c9b.firebaseapp.com',
    storageBucket: 'chatapp-29c9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzwyyPWkYXEmRsi6-0EuwRkIMBZ2ySKus',
    appId: '1:588349736392:android:f1b177e84f5cb09df6ecfd',
    messagingSenderId: '588349736392',
    projectId: 'chatapp-29c9b',
    storageBucket: 'chatapp-29c9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX2UsmwTljyq_8Io4kuolPUmsa0TFC-So',
    appId: '1:588349736392:ios:eda19b2b5cdbbdcaf6ecfd',
    messagingSenderId: '588349736392',
    projectId: 'chatapp-29c9b',
    storageBucket: 'chatapp-29c9b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX2UsmwTljyq_8Io4kuolPUmsa0TFC-So',
    appId: '1:588349736392:ios:7b2e20f9129164b4f6ecfd',
    messagingSenderId: '588349736392',
    projectId: 'chatapp-29c9b',
    storageBucket: 'chatapp-29c9b.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
